In [1]:
import numpy as np

B = np.array(2, dtype=np.float32)

In [3]:
B

array(2., dtype=float32)

In [6]:
B_list = [B.copy() for _ in range(10)]
B_list

[array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32),
 array(2., dtype=float32)]

In [10]:
import bisect
import numpy as np


p = np.array([0.1, 0.1, 0.1, 0.1], dtype=np.float32)
p_cumsum = np.cumsum(p) / np.sum(p)
print("Cumulative sum of probabilities:", p_cumsum)


xi = np.random.uniform(0, 1)
idx = bisect.bisect_left(p_cumsum, xi)
print(f"Random value: {xi}, Index in cumulative sum: {idx}")

Cumulative sum of probabilities: [0.25 0.5  0.75 1.  ]
Random value: 0.9689434508756708, Index in cumulative sum: 3


In [3]:
import itertools
import numpy as np

def generate_price_combinations(self, f_split):
    combos = list(itertools.product(*f_split))
    return np.array(combos, dtype=float)

In [4]:
f_split = [
    [1.0, 2.0],
    [3.0, 4.0, 5.0],
    [5.0, 6.0]
]
price_combinations = generate_price_combinations(None, f_split)
print("Generated price combinations:")
print(price_combinations)

Generated price combinations:
[[1. 3. 5.]
 [1. 3. 6.]
 [1. 4. 5.]
 [1. 4. 6.]
 [1. 5. 5.]
 [1. 5. 6.]
 [2. 3. 5.]
 [2. 3. 6.]
 [2. 4. 5.]
 [2. 4. 6.]
 [2. 5. 5.]
 [2. 5. 6.]]


In [1]:
import numpy as np

f = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=object)
p = np.array([[1, 1], [1, 1], [1, 1]], dtype=object)
c = -np.sum(f * p, axis=0)
c

array([-9.0, -12.0], dtype=object)

In [2]:
import bisect

a = [0, 1, 2]
bisect.bisect_left(a, 20)

3

In [3]:
# generate a list of 25 random int numbers from 3 to 13
import random
random_list = [random.randint(3, 13) for _ in range(25)]
print(random_list)

[9, 7, 8, 7, 11, 8, 7, 6, 7, 7, 5, 12, 8, 11, 8, 12, 9, 8, 10, 4, 12, 6, 9, 3, 12]
